[package]
name = "all_calls_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.4.0"
syn = { version = "2.0", features = ["full"] }
csv = "1.1"

[build-dependencies]
walkdir = "2.4.0"
syn = { version = "2.0", features = ["full"] }
csv = "1.1"